### ISSUE TITLE
LGTM not triggered till a comment is written

### ISSUE THREAD

**Issue by donny-dont** [lgtmco/lgtm#1] opened 2016-01-25 22:53 UTC
The status check is not present until a comment is written. Then the status check is triggered. Thinking maybe LGTM should get a pull request notification.

Currently using GHE 2.4.x.

**Comment by bradrydzewski** [comment] 2016-04-13 18:31
I'm going to close this since newer versions of GitHub automatically add the status check now

**Closed as completed by bradrydzewski** 2016-04-13 18:31 UTC

**Comment by benlangfeld** [comment] 2016-05-27 18:05
We're still seeing exactly this issue. Is the expectation that the status be required to be passing for merges for this to work? We'd like to keep LGTM as advisory at this point, but we do want people merging PRs to be aware that approval was not yet received.

**Comment by bradrydzewski** [comment] 2016-05-27 18:07
@benlangfeld are you using GitHub Enterprise? Because this is not the case with the latest version of GitHub. You can see, for example, GitHub has automatically added the status check to the below pull request which has no comments yet:
https://github.com/drone-plugins/drone-containership/pull/9

**Comment by benlangfeld** [comment] 2016-05-27 18:08
We're using public GitHub and do not see that behaviour; it is broken for us.

**Comment by bradrydzewski** [comment] 2016-05-27 18:10
Attached a screenshot of what I see below.

@benlangfeld the status is added by GitHub automatically and LGTM is not involved at all. GitHub automatically populates all required status checks when the PR is created. If this isn't happening for your repository I recommend contacting GitHub support.

---

<img width="595" alt="screen shot 2016-05-27 at 11 08 45 am" src="https://cloud.githubusercontent.com/assets/817538/15616933/6c5aa4c4-23fb-11e6-8fa5-050461057084.png">

**Comment by benlangfeld** [comment] 2016-05-27 18:11
Thanks @bradrydzewski, I will take it up with Github :) /cc @bklang

**Comment by bradrydzewski** [comment] 2016-05-27 18:13
thanks! feel free to post back your conversation with GitHub support so we can better understand the root cause, and perhaps why we both see two different behaviors! I wish I could be more help, but in this case GitHub is a bit of a black box :)

**Comment by bklang** [comment] 2016-05-27 18:27
This just happened to me again using public Github (with a private repo). I'll drop a screenshot here as documentation:

<img width="534" alt="schermata 2016-05-27 alle 2 25 53 pm" src="https://cloud.githubusercontent.com/assets/167131/15617462/11ff1af2-2417-11e6-895d-3b19f96ab471.png">

Note that the LGTM check isn't visible, but it appears as soon as any comment is made on the PR.

**Comment by donny-dont** [comment] 2016-05-27 18:33
Check the installed hooks? Maybe something didn't get enabled

**Comment by bklang** [comment] 2016-05-27 18:35
<img width="765" alt="schermata 2016-05-27 alle 2 34 28 pm" src="https://cloud.githubusercontent.com/assets/167131/15617721/240deed4-2418-11e6-82be-d92739ee1e9d.png">

The original configured webhook was only configured to be called when a comment was created/edited/deleted. I changed it to send All events, but the broken behavior persists.

**Comment by bradrydzewski** [comment] 2016-05-27 18:42
@bklang @donny-dont 

LGTM does not receive a hook until the first comment is made. So this isn't really a question of whether or not LGTM hooks are working properly because LGTM is not involved in the process yet, until that first comment is received. The question is why GitHub is not automatically adding the required status check to your pull request, but is adding it to mine (based on my above screenshot).

This logic seems to sit somewhere inside of GitHub.

**Comment by bradrydzewski** [comment] 2016-05-27 18:45
Note that I'm not claiming there isn't something to be improved here in LGTM. I'm just not able to reproduce with my own repositories. I can clearly see, based on the two screenshots, that we are experiencing different behavior so I'm not saying there isn't any issue.

I think it would be good to understand what is happening here in GitHub before we try to fix something in LGTM.

**Comment by benlangfeld** [comment] 2016-06-02 18:35
@bradrydzewski The response from Github:

> Rachel Berry (GitHub Staff) to Ben, Ben
> 14:33
> Hi Ben,
> 
> Thanks for permission to take a look. I've discovered where the confusion is coming from, and it seems like @benlangfeld actually brought this up on the LGTM issue before:
> 
> https://github.com/lgtmco/lgtm/issues/1#issuecomment-222214740
> 
> We automatically display status checks on PRs, that's true, but _only_ if they're set as a _required_ status check. Otherwise we wait to receive an event before posting any status at all.
> 
> That explains the discrepancy you're seeing between your PRs:
> https://github.com/powerhome/nitro-web/pull/2316
> 
> And the sample PR they pointed you to:
> https://github.com/drone-plugins/drone-containership/pull/9
> 
> Their sample has the status check set to _required_, but the "powerhome/nitro-web" repo has it as optional. That means for your repo, we're waiting to hear from LGTM before posting a status to the PR.
> 
> One possible solution if you don't want to make the check 'required' might be for LGTM to send a 'pending' status after they receive our webhook for the initial PR creation, and then update that status once they detect the LGTM comment they're waiting for.
> 
> Hope that clears everything up! Let me know if you have any additional questions.
> 
> All the best,
> Rachel

**Comment by bradrydzewski** [comment] 2016-06-02 18:43
@benlangfeld thanks for that information it is indeed helpful. I configured a new repository with LGTM and was able to verify the `approvals/lgtm` status check is configured as required, by default. I then disabled / re-enabled to verify the status check was still labeled as required.

Is is possible someone changed this behavior manually for your repository to make the check optional?

<img width="756" alt="screen shot 2016-06-02 at 11 39 12 am" src="https://cloud.githubusercontent.com/assets/817538/15756577/bcf95410-28b6-11e6-86b0-a63e536f3846.png">

**Comment by benlangfeld** [comment] 2016-06-02 19:13
Yes, we did @bradrydzewski. We actively want the check to be optional, per https://github.com/lgtmco/lgtm/issues/1#issuecomment-222214740. We have a large team we're trying to train to do better code review, but it needs to be a gradual ramp up. Right now LGTM is invisible, but we can't yet enforce it.

**Comment by bradrydzewski** [comment] 2016-06-02 19:21
@benlangfeld I definitely understand your use case, however, integrating with protected branches and **enforcing** approvals is the software's primary purpose. The software is not intended to be used with optional approvals. I would therefore recommend forking the project and altering the behavior to meet your teams individual needs.

**Comment by benlangfeld** [comment] 2016-06-02 19:34
If we contributed Rachel / @donny-dont's suggestion, would that be included upstream? It seems like the current implementation is simply the minimum that satisfies the original use case, and while this would not have any user-facing difference for that original use case, it would fairly cleanly add support for mine / @donny-dont's.

**Comment by bradrydzewski** [comment] 2016-06-02 19:37
@benlangfeld sure, once you have an initial version feel free to submit a pull request for review. cheers!

**Comment by donny-dont** [comment] 2016-06-02 20:31
We updated our GHE so were pretty good to go on this.
